### ISSUE TITLE
Filter unknow CSS properties which become not-unknown with a vendor prefix

### ISSUE THREAD

**Issue by wheany** [operasoftware/dragonfly#98]
If I have a CSS block such as:

``` css
div
 {
 -moz-transition-property: width;
 -webkit-transition-property:width;
 -o-transition-property:width;
 transition-property:width;
 }
```

The error console shows the following error (with vendor-prefix filtering on):

```
transition-property is an unknown property
    transition-property: width;
  ----------------------^
```

Add option to filter CSS properties which become known properties when prepended with -o-.
